<div class="">
  <center>
    <div class="container-fluid">
      <div class="row">
        <div class="p-0 col-md-4 col-6">
          <img src="https://www.picz.in.th/images/2018/01/31/0159547dca3a2383b7.jpg" alt="0159547dca3a2383b7.jpg" border="0" class="img-fluid float-right" height="" width="450"> </div>
        <div class="col-md-4 col-6 p-0">
          <img src="https://www.picz.in.th/images/2018/01/31/030f4dd37b426a62b9.jpg" alt="030f4dd37b426a62b9.jpg" border="0" class="img-fluid" width="450"> </div>
        <div class="col-md-4 col-6 p-0">
          <img src="https://www.picz.in.th/images/2018/01/31/04d1feb37e68365001.jpg" alt="04d1feb37e68365001.jpg" border="0" class="img-fluid float-left" width="450"> </div>
        <div class="col-md-4 col-6 p-0">
          <img src="https://www.picz.in.th/images/2018/01/31/0520a45b414c8cb4b3.jpg" alt="0520a45b414c8cb4b3.jpg" border="0" class="img-fluid float-right" width="450"> </div>
        <div class="col-md-4 col-6 p-0">
          <img src="https://www.picz.in.th/images/2018/01/31/072cc48632d187f498.jpg" alt="072cc48632d187f498.jpg" border="0" class="img-fluid" width="450"> </div>
        <div class="col-md-4 col-6 p-0">
          <img src="https://www.picz.in.th/images/2018/01/31/08f3885440b1b14a5d.jpg" alt="08f3885440b1b14a5d.jpg" border="0" class="img-fluid float-left rounded" width="450"> </div>
      </div>
    </div>
  </center>
</div>
<div class="py-5 text-center bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="pb-3 text-secondary">" We will take care of your pets as well "</h1>
      </div>
    </div>
    <div class="row">
      <div class="text-right col-md-6">
        <div class="row my-5">
          <div class="col-2 order-lg-2 col-2 text-center"><i class="d-block fa fa-3x fa-heart-o"></i></div>
          <div class="col-10 text-lg-right text-left order-lg-1">
            <h4 class="text-primary">เมื่อเราไม่อยู่บ้านเราก็เป็นห่วงเค้า</h4>
            <p>When we are not home, we worry.</p>
          </div>
        </div>
        <div class="row my-5">
          <div class="col-2 order-lg-2 col-2 text-center"><i class="d-block fa fa-4x fa-ambulance"></i></div>
          <div class="col-10 text-lg-right text-left order-lg-1">
            <h4 class="text-primary">เป็นห่วงว่าเค้าจะสบายดีหรือเปล่า</h4>
            <p>Are you worried that he will be fine?</p>
          </div>
        </div>
      </div>
      <div class="text-left col-md-6">
        <div class="row my-5">
          <div class="col-2 text-center"><i class="d-block fa fa-battery-empty fa-3x"></i></div>
          <div class="col-10">
            <h4 class="text-primary">กลัวว่าเค้าจะได้กินอิ่มรึเปล่าเวลาเราไม่ว่าง</h4>
            <p>I'm afraid that I will not eat when we are busy.</p>
          </div>
        </div>
        <div class="row my-5">
          <div class="col-2 text-center"><i class="d-block mx-auto fa  fa-3x fa-gamepad"></i></div>
          <div class="col-10">
            <h4 class="text-primary">จะมีใครเล่นอยู่เป็นเพื่อนเค้าใหม</h4>
            <p>I have a friend who is a friend.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <font face="TH SarabunPSK">
        <font size="6">
          <p>ให้พวกเราช่วยคุณดูแลเค้าสิ!</p>
          <p>พวกเราจะช่วยคุณดูแลเค้าเวลาคุณไม่ว่าง</p>
          <p>พวกเราจะดูแลเค้าถ้าเค้าไม่สบาย</p>
          <p>พวกเราจะทำให้เค้ามีความสุขและสนุก</p>
          <p>เพราะพวกเรารักเค้าเหมือนที่คุณรัก</p>
          <p>อย่าลืมพวกเราละ PET CARRIE</p>
        </font>
      </font>
    </div>
    <font face="TH SarabunPSK">
      <font face=""> </font>
    </font>
  </div>
  <font face="TH SarabunPSK">
    <font face=""> </font>
  </font>
</div>
<font face="TH SarabunPSK">
  <font face="">
    <div class="py-5">
      <div class="container">
        <div class="row"> </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 10px;right:10px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:180px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo&nbsp;&nbsp;
      <img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16">
    </pingendo>
  </font>
</font>
