

<div class="container">
    <div class="row">
      <?php foreach ($carrier as $care): ?>

        <div class="col-sm-6 col-md-4 col-lg-4 mt-4">
            <div class="card">
                <div class="card-block ">
                    <figure class=" text-center">
                        <img src="<?=$care->img; ?>" width="150px" height="180px" class="" alt="">
                    </figure>
                </div>
                <h4 class="card-title pl-3"><?=$care->firstname; ?>  &nbsp; <?=$care->lastname; ?></h4>

                <div class="card-footer pb-3">
                    <p>เขตที่ดูแล : <?=$care->city; ?> , <?=$care->province; ?></p>
                    <p>ความชำนาญ : <?=$care->skill; ?>&nbsp;</p>
                    <p>อายุ : <?=$care->age; ?></p>
                    <a href="<?=$this->url->get('carrier/rent/'.$care->id)?>" class="btn btn-success" type="submit">เลือก</a>
                    <a href="<?=$this->url->get('carrier/profile/'.$care->id)?>" class="btn btn-info">รายละเอียด</a>
                </div>
            </div>
        </div>
      <?php endforeach; ?>
    </div>
    <br>
</div>
